// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:project_tmp/data/models/app_state.dart';
import 'package:project_tmp/data/models/setting.dart';
import 'package:project_tmp/data/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppStateAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppStateAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(UserAdapter());
  }
}
